# Generated by Django 4.2.11 on 2025-10-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqcoin_app', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
