# Generated by Django 5.2.5 on 2025-10-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqcoin_app', '0004_student_is_active_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
