# Generated by Django 4.2.11 on 2025-11-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqcoin_app', '0009_alter_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code (e.g., #FF5733)', max_length=7, null=True),
        ),
    ]
