# Generated by Django 5.2.5 on 2025-12-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqcoin_app', '0011_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('AWARD', 'Награда'), ('DEDUCT', 'Списание')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('parent', 'Родитель'), ('teacher', 'Учитель'), ('admin', 'Администратор')], default='teacher', max_length=10),
        ),
    ]
